# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_trails_cpp <- function(field_df, particles_df, width, height, steps, step_length, min_dist, seed) {
    .Call('_flow_make_trails_cpp', PACKAGE = 'flow', field_df, particles_df, width, height, steps, step_length, min_dist, seed)
}

pack_circles_cpp <- function(width, height, max_circles, r, max_attempts = 2000L, seed = 1L) {
    .Call('_flow_pack_circles_cpp', PACKAGE = 'flow', width, height, max_circles, r, max_attempts, seed)
}

