# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_long_trail <- function(x0, y0, flowfield, existing_points, step_length, dtest, max_steps = 1000L) {
    .Call(`_flow_make_long_trail`, x0, y0, flowfield, existing_points, step_length, dtest, max_steps)
}

make_trail <- function(x0, y0, field_df, existing_points, step_length = 1, max_steps = 1000L, direction = "both", dtest = 1) {
    .Call(`_flow_make_trail`, x0, y0, field_df, existing_points, step_length, max_steps, direction, dtest)
}

make_trails_rcpp <- function(particles, field_df, step_length = 1, max_steps = 1000L, direction = "both", dtest = 1) {
    .Call(`_flow_make_trails_rcpp`, particles, field_df, step_length, max_steps, direction, dtest)
}

get_angle2 <- function(x, y, w) {
    .Call(`_flow_get_angle2`, x, y, w)
}

check_neighbors <- function(x, y, existing_points, dtest) {
    .Call(`_flow_check_neighbors`, x, y, existing_points, dtest)
}

update_current_seeds <- function(line, flowfield_df, dsep) {
    .Call(`_flow_update_current_seeds`, line, flowfield_df, dsep)
}

grow <- function(len) {
    .Call(`_flow_grow`, len)
}

grow2 <- function(len) {
    .Call(`_flow_grow2`, len)
}

grow3 <- function(len) {
    .Call(`_flow_grow3`, len)
}

grow_rev <- function(steps) {
    .Call(`_flow_grow_rev`, steps)
}

rever <- function(seq) {
    .Call(`_flow_rever`, seq)
}

pack_circles_cpp <- function(width, height, max_circles, r, max_attempts = 2000L, seed = 1L) {
    .Call(`_flow_pack_circles_cpp`, width, height, max_circles, r, max_attempts, seed)
}

